version: '3.8'
services:
  frontend:
    build: .
    container_name: inventory-frontend
    ports:
      - "8082:80"
    restart: unless-stopped
  networks:
    inventory-network:
      external: true
      name: turing-backend_inventory-network  <-- AÑADE ESTA LÍNEA EXACTA

networks:
  inventory-network:
    external: true
